### ISSUE TITLE
Location header should respect X-Forwarded-Proto

### ISSUE THREAD

**Issue by bt90** [nosduco/nforwardauth#24]
The redirect only alters the scheme of the service URL. The URL of nforwardauth itself is hardcoded to `http://`

![grafik](https://github.com/nosduco/nforwardauth/assets/1926175/964d7fe1-83fb-4a40-92e1-f6a16203f4fb)

Could we use the same scheme for both? e.g.

```rust
    let scheme = if headers.contains_key(FORWARDED_PROTO) && !headers[FORWARDED_PROTO].is_empty()
    {
        headers[FORWARDED_PROTO].to_str().unwrap()
    } else {
        "http"
    };

    // No valid cookie/jwt found, create redirect url and return
    let mut location =
        Url::parse(format!("{}://{}/login", scheme, &Config::global().auth_host).as_str())?;
```

**Comment by nosduco** [comment]
Great catch, will tackle this tonight/tomorrow. The plan was to respect it, must have slipped my mind and only respected it for the referral.
