### ISSUE TITLE
Very minor: malicious behavior can cause panics of handler threads

### ISSUE THREAD

**Issue by shimaowo** [nosduco/nforwardauth#34]
This isn't realistically any kind of problem, but I thought I'd point it out anyway.

It is possible for an attacker to cause the handler thread for their connection to panic. Tokio etc handle this fine, and the server itself does not suffer, but it does spam the console/logs with typical rust panic messaging.

A common malicious attack with JWT cookies is to manually edit the signature field in the header to use "none" and to then remove the signature part, because some sites/libraries are poorly made and don't validate things.

The libraries in this project handle that fine. However, [this unwrap()](https://github.com/nosduco/nforwardauth/blob/main/src/main.rs#L79) is hit when the relevant error is thrown, which causes the panic. It might be slightly nicer to catch that and just let the code continue as unauthorized.

But it's pretty unlikely anyone would ever legitimately trigger this, as only authed users see the cookie in the first place, and they obviously have no reason to manipulate it.

**Comment by nosduco** [comment]
Great call out! Much appreciated. I found the commit on your fork and cherry-picked it (and changed a tad) on #40
