### ISSUE TITLE
Add an executable to git release

### ISSUE THREAD

**Issue by LudovicLachance** [nosduco/nforwardauth#42]
Would it be possible to add a release that is not using docker to build it and run it?

**Comment by nosduco** [comment]
Hey @LudovicLachance ! Thanks for the request. I went ahead and added automatic Linux builds that are attached to the GitHub releases now. You can take a look at the newest version here: https://github.com/nosduco/nforwardauth/releases/tag/v1.3.4

Does this achieve what you were looking for?
