### ISSUE TITLE
How is it any different than oauth2-proxy

### ISSUE THREAD

**Issue by amit-yp** [nosduco/nforwardauth#7]
- [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) has similar functionality
- other than being written in rust(which would certainly make it faster) what are the benefits of using this?

**Comment by nosduco** [comment]
This is not OAuth at all. You store passwords into a `passwd` file and use the login form or basic auth to pass your credentials. This requires no IdP (Identity Provider) as it acts as both the IdP and forwardauth service. Hope this helps!
