### ISSUE TITLE
Prevent bruteforce attacks

### ISSUE THREAD

**Issue by bt90** [nosduco/nforwardauth#8]
Could you add a rate-limiter like https://crates.io/crates/governor/ to prevent bruteforce attacks?

The server should answer login attempts with HTTP 429 after hitting a limit.

**Comment by nosduco** [comment]
Thanks for the issue submission, this is definitely important. However, upon some docs reading seems like I will need to refactor a bit to be able to grab the IP inside the main service function. Will prioritize this and keep this issue updated!

**Comment by bt90** [comment]
You should be able to obtain the client IP via the `X-Forwarded-For` or `X-Real-IP` headers.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#parsing

**Comment by nosduco** [comment]
Yes, but rate limiting off of those would be bad, no? Those can be spoofed. I guess generally it would be _fine_, but if a malicious actor is trying to brute force I'd much rather rate limit based on the IP tied to the TCP connection.

**Comment by otbutz** [comment]
Wouldn't you just get the IP of the reverse proxy?

**Comment by nosduco** [comment]
@bt90 Good finds! Thanks for the links, I'm struggling to see where Caddy sends the `X-Forwarded-For` header tho.

Seems like you may need to add something like `header_up X-Forwarded-For {host}` to the `forward_auth` directive?

**Comment by nosduco** [comment]
Gotcha! Good stuff, thanks for the confirmation. Additional question, what configuration options do you think should be exposed with the rate limiter? Also, due to the nature of the forward auth and how it will get passed every request, the login route should be the only one rate limited, or do you suggest otherwise?

**Comment by bt90** [comment]
I would limit failed login attempts per IPv4 or IPv6 /64 subnet and provide the following adjustable values:

* number of login attempts
* monitored duration
* ban time

**Comment by bt90** [comment]
If we can't adjust the bantime, i think something like 3 login attempts per minute is reasonable.

That would limit an attacker to around ~4300 attempts per day.

**Comment by nosduco** [comment]
Sweet! Sounds good, thank you for the requests. I'll work on this over the weekend/early next week.

**Comment by bt90** [comment]
For reference, authelia seems to use these defaults:

```yml
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
```
